//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_wpf_
{
    using System;
    using System.Collections.Generic;
    
    public partial class languagesForGame
    {
        public int idLanguagesForGame { get; set; }
        public int idLanguage { get; set; }
        public int idGame { get; set; }
    
        public virtual games games { get; set; }
        public virtual languages languages { get; set; }
    }
}
