//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_wpf_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class steamEntities : DbContext
    {
        public steamEntities()
            : base("name=steamEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<developers> developers { get; set; }
        public virtual DbSet<developersForGame> developersForGame { get; set; }
        public virtual DbSet<games> games { get; set; }
        public virtual DbSet<genres> genres { get; set; }
        public virtual DbSet<genresForGame> genresForGame { get; set; }
        public virtual DbSet<languages> languages { get; set; }
        public virtual DbSet<languagesForGame> languagesForGame { get; set; }
        public virtual DbSet<publishers> publishers { get; set; }
        public virtual DbSet<publishersForGame> publishersForGame { get; set; }
        public virtual DbSet<reviews> reviews { get; set; }
        public virtual DbSet<tags> tags { get; set; }
        public virtual DbSet<tagsForGame> tagsForGame { get; set; }
        public virtual DbSet<userLibrary> userLibrary { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
