//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_wpf_
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int idReview { get; set; }
        public int idGame { get; set; }
        public string reviewDesccription { get; set; }
        public bool rating { get; set; }
        public int idUser { get; set; }
        public Nullable<System.DateTime> publicationDate { get; set; }
    
        public virtual games games { get; set; }
        public virtual users users { get; set; }
        public virtual reviews reviews1 { get; set; }
        public virtual reviews reviews2 { get; set; }
    }
}
