//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Steam_wpf_
{
    using System;
    using System.Collections.Generic;
    
    public partial class userLibrary
    {
        public int idLibraryGame { get; set; }
        public int idUser { get; set; }
        public int idGame { get; set; }
        public double userPlayedTime { get; set; }
    
        public virtual games games { get; set; }
        public virtual users users { get; set; }
    }
}
